title: "[New Component]: "
labels: "enhancement"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new component to Prism UI!

  - type: textarea
    id: component-description
    attributes:
      label: Component Description
      description: Describe the purpose and functionality of this component
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Please provide examples of similar components from other design systems or websites

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this component needed?
      options:
        - High (Blocking work)
        - Medium (Needed soon)
        - Low (Nice to have)
    validations:
      required: true

  - type: input
    id: figma-link
    attributes:
      label: Figma Design Link
      description: Link to the Figma design if available
      placeholder: "https://www.figma.com/file/..."

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or design mockups

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm you have completed the following steps before submitting the bug report
      options:
        - label: I have checked that the component does not already exist
          required: true
        - label: I have searched the existing issues and confirmed this is not a duplicate
          required: true
